# Generated by Django 4.1.1 on 2022-09-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_watchedmovie_remove_movie_raters_delete_movierating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(default="United States", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(default="English", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="plot",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.TimeField(default="01:00"),
            preserve_default=False,
        ),
    ]
