# Generated by Django 4.1.1 on 2022-09-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies",
            "0003_rename_name_movie_title_movie_country_movie_language_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="image",
            new_name="poster",
        ),
    ]
