# Generated by Django 4.1.1 on 2022-09-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_rename_image_movie_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
    ]
