# Generated by Django 4.1.1 on 2022-09-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_movie_poster_movie_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
