# Generated by Django 4.1.1 on 2022-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_movie_tmdb_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo_url", models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="actor",
            name="image",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="streaming",
        ),
        migrations.AddField(
            model_name="actor",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="backdrop_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="watch_providers",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.watchprovider"
            ),
        ),
    ]
