# Generated by Django 4.1.1 on 2022-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_watchprovider_remove_actor_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
