# Generated by Django 4.1.1 on 2022-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_imdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(max_length=255),
        ),
    ]
