# Generated by Django 4.1.1 on 2022-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_movie_imdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="tmdb_id",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
