# Generated by Django 4.1.1 on 2022-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_genre_tmdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="tmdb_id",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="director",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="director",
            name="tmdb_id",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchprovider",
            name="tmdb_id",
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
