# Generated by Django 4.1.1 on 2022-09-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_alter_movie_imdb_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rotten_tomatoes_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
