# Generated by Django 4.1.1 on 2022-09-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="backdrop_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
