# Generated by Django 4.1.1 on 2022-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_alter_movie_backdrop_url_alter_movie_poster_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedmovie",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Awful"), (2, "Meh"), (3, "Good"), (4, "Amazing")],
            ),
        ),
    ]
