# Generated by Django 4.1.1 on 2022-09-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0017_alter_movie_country_alter_movie_imdb_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
