# Generated by Django 4.1.1 on 2022-09-27 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0018_alter_movie_runtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tmdb_id", models.IntegerField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "user_saves",
                    models.ManyToManyField(
                        blank=True,
                        related_name="saved_production_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="production_companies",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movies.productioncompany"
            ),
        ),
    ]
