# Generated by Django 4.1.1 on 2022-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0019_productioncompany_movie_production_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_now_playing",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_popular",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_trending",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_upcoming",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
