# Generated by Django 4.1.1 on 2022-10-01 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0020_movie_is_now_playing_movie_is_popular_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedmovie",
            name="date_saved",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
