# Generated by Django 4.0.7 on 2022-10-05 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0022_remove_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprovider',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='streaming_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
